# Based on: https://github.com/census-instrumentation/opencensus-erlang/blob/5e697cd/.circleci/config.yml
version: 2.1

orbs:
  rebar3: tsloughter/rebar3@0.7.0

jobs:
  build_and_test:
    parameters:
      tag:
        description: The Erlang/OTP docker image tag to use
        type: string
    executor:
      name: rebar3/erlang
      tag: <<parameters.tag>>
    steps:
      - checkout
      - run:
          name: "Clone submodules"
          command: |
            git submodule update --init --recursive
      - rebar3/with_deps_cache:
          cache_key_postfix: -<<parameters.tag>>
          steps:
            - run: RUNNING_ON_CI=yes make ci_test

            - store_test_results:
                path: ~/project/_build/test/logs/
            - store_artifacts:
                path: ~/project/_build/test/logs
                destination: common_test

workflows:
  run_all:
    jobs:
      - build_and_test:
          name: "otp-18"
          tag: "18.3"
