---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: >
      Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: ['22.0', '22.1', '22.2', '22.3',
                  '23.0', '23.1', '23.2', '23.3',
                  '24.0', '24.1', '24.2', '24.3']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: RUNNING_ON_CI=yes make check ci_test
