---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: >
      Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: [19.0, 19.3,
                  20.0, 20.1, 20.3,
                  21.0, 21.1, 21.2, 21.3,
                  22.0, 22.1, 22.2, 22.3,
                  23.0]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: RUNNING_ON_CI=yes make ci_test
